version: '3'
services:
  flask:
    build: .
    #image: stateless_app_ex_flask
    ports:
      - "5001:5000"
    environment:
      POSTGRES_HOST: postgres
    env_file: database.conf
  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    ports:
    - 5432:5432
    env_file: database.conf
